CREATE DATABASE IF NOT EXISTS bressan_financeira DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE bressan_financeira;

CREATE TABLE IF NOT EXISTS clientes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(180) NOT NULL,
  email VARCHAR(180) NOT NULL,
  telefone VARCHAR(60) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS cartas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  titulo VARCHAR(220) NOT NULL,
  categoria VARCHAR(80) NOT NULL,
  descricao TEXT,
  valor DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  status ENUM('disponivel','reservada','vendida') NOT NULL DEFAULT 'disponivel',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS simulacoes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(180) NOT NULL,
  email VARCHAR(180) NOT NULL,
  telefone VARCHAR(60) DEFAULT NULL,
  tipo VARCHAR(120) NOT NULL,
  valor_solicitado DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  mensagem TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS reservas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  cliente_id INT NOT NULL,
  carta_id INT NOT NULL,
  status ENUM('pendente','confirmada','cancelada') NOT NULL DEFAULT 'pendente',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE,
  FOREIGN KEY (carta_id) REFERENCES cartas(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS mensagens (
  id INT AUTO_INCREMENT PRIMARY KEY,
  cliente_id INT DEFAULT NULL,
  assunto VARCHAR(220) NOT NULL,
  mensagem TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE SET NULL
) ENGINE=InnoDB;
